AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: HelloWorld/lambda_function.lambda_handler
      FunctionName: HelloWorld
      Runtime: python3.6
      Description: 'This is my super duper HelloWorld function!'
      MemorySize: 128
      Timeout: 15
      CodeUri: .debug/
